# Generated by Django 2.2.2 on 2019-06-26 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_user', models.CharField(choices=[('egresado', 'egresado'), ('admin', 'admin'), ('superadmin', 'superadmin')], default='egresado', max_length=100, verbose_name='Tipo de usuario')),
                ('website', models.URLField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=12)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='users/pictures')),
                ('city', models.TextField(max_length=20)),
                ('dni_administrador', models.CharField(max_length=20)),
                ('interests', models.TextField(blank=True)),
                ('age', models.CharField(default=0, max_length=2)),
                ('gender', models.CharField(choices=[('indef', 'Indefinido'), ('masc', 'Masculino'), ('fem', 'Femenino')], default='indef', max_length=4)),
                ('confirmation_handling_sensitive_data', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
