# Generated by Django 2.2.2 on 2019-06-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='authorized',
            field=models.BooleanField(default=False, verbose_name='Acceso autorizado'),
        ),
    ]
