# Generated by Django 2.0.2 on 2019-07-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='interests',
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(related_name='interested_students', to='users.Subject'),
        ),
    ]
