# Generated by Django 2.0.2 on 2019-07-12 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190711_2225'),
        ('users', '0007_auto_20190712_0134'),
    ]

    operations = [
    ]
