# Generated by Django 2.0.2 on 2019-07-12 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_biography'),
        ('users', '0008_merge_20190712_0308'),
    ]

    operations = [
    ]
